on: workflow_dispatch

jobs:
  deploy-to-gist:
    name: deploy-to-gist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: pavelkotsikau/03b1ed5602f6940a0d97085eaca72ae8
          file_path: ./README.md
          file_type: binary
